sonar.projectKey=yoyui-local
sonar.projectName=YoYui Local
sonar.projectVersion=local

sonar.sources=components,pages,service,api-scripts
sonar.tests=components
sonar.exclusions=**/*.spec.js,**/__snapshots__/**,components/test/**,**/*.gif,**/*.tsbuildinfo
sonar.test.inclusions=**/*.spec.js,components/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.node.maxspace=8192
sonar.scm.disabled=true
sonar.sourceEncoding=UTF-8
